### ISSUE TITLE
タスク完了機能

### ISSUE THREAD

**Issue by ysku** [hisoka0620/laravel_with_vue3_tutorial#1]
### 要件概要

- 現在のタスク一覧画面に「完了」ボタンを追加する
- 「完了」したものはタスク一覧画面には表示しない
- タスク一覧画面とは別に「完了」したタスク一覧を作成する
- 完了したタスク一覧画面に「戻す」ボタンを用意して、それが押されるとタスク一覧画面に表示されるようにする（完了したタスク一覧には表示されないようにする）

### 工数見積もり

xx 時間

*見積もりと合わなかった理由 ( 合わなかった場合 )*

- xxx
- xxx
- xxx

### 納期

明日 5/15 23:59

**Comment by hisoka0620** [comment]
見積もりと合わなかった理由

・なんの根拠もない自信で一日でできるだろうという甘い考えでいたこと。
・作業を始めてみてコードを書けない（うまく実装できない）の痛感したこと。

**Comment by ysku** [comment]
具体的にどこで思ってたより時間かかってしまった？
